CREATE TABLE IF NOT EXISTS leads (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  whatsapp VARCHAR(50) NOT NULL,
  origem VARCHAR(100) NOT NULL DEFAULT 'landing_free_plan',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
