import { pgTable, text, serial, timestamp, integer, varchar, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { tenantsTable } from "./tenants";

export const dentalSettingsTable = pgTable("dental_settings", {
  id: serial("id").primaryKey(),
  tenantId: integer("tenant_id").notNull().references(() => tenantsTable.id, { onDelete: "cascade" }).unique(),
  clinicName: varchar("clinic_name", { length: 255 }),
  clinicPhone: varchar("clinic_phone", { length: 50 }),
  clinicAddress: text("clinic_address"),
  professionalName: varchar("professional_name", { length: 255 }),
  professionalCro: varchar("professional_cro", { length: 20 }),
  professionalSpecialties: text("professional_specialties"),
  professionalGender: varchar("professional_gender", { length: 20 }),
  specialties: text("specialties"),
  workingHoursStart: varchar("working_hours_start", { length: 5 }).notNull().default("08:00"),
  workingHoursEnd: varchar("working_hours_end", { length: 5 }).notNull().default("18:00"),
  workingDays: text("working_days").notNull().default("1,2,3,4,5"),
  slotDurationMinutes: integer("slot_duration_minutes").notNull().default(30),
  defaultLeadDurationMinutes: integer("default_lead_duration_minutes").notNull().default(15),
  defaultPatientDurationMinutes: integer("default_patient_duration_minutes").notNull().default(30),
  chargesConsultation: boolean("charges_consultation").notNull().default(true),
  consultationFee: varchar("consultation_fee", { length: 20 }).notNull().default("150.00"),
  autoConfirmAppointments: boolean("auto_confirm_appointments").notNull().default(true),
  confirmDaysBefore: integer("confirm_days_before").notNull().default(1),
  acceptsInsurance: boolean("accepts_insurance").notNull().default(false),
  insurancePlans: text("insurance_plans"),
  insuranceDays: text("insurance_days"),
  insuranceHoursStart: varchar("insurance_hours_start", { length: 5 }),
  insuranceHoursEnd: varchar("insurance_hours_end", { length: 5 }),
  lunchStart: varchar("lunch_start", { length: 5 }).notNull().default("12:00"),
  lunchEnd: varchar("lunch_end", { length: 5 }).notNull().default("13:00"),
  scheduleConfig: text("schedule_config"),
  aiName: varchar("ai_name", { length: 100 }).notNull().default("Secretária IA"),
  aiPersonality: text("ai_personality"),
  personalityType: varchar("personality_type", { length: 20 }),
  aiLanguage: varchar("ai_language", { length: 10 }).notNull().default("pt-BR"),
  reminderHoursBefore: integer("reminder_hours_before").notNull().default(24),
  remarketingEnabled: boolean("remarketing_enabled").notNull().default(true),
  remarketingHours: varchar("remarketing_hours", { length: 20 }).notNull().default("10,15"),
  remarketingDays: varchar("remarketing_days", { length: 20 }).notNull().default("1,2,3,4,5,6"),
  remarketingMaxLeads: integer("remarketing_max_leads").notNull().default(10),
  remarketingIntervalHot: integer("remarketing_interval_hot").notNull().default(2),
  remarketingIntervalWarm: integer("remarketing_interval_warm").notNull().default(4),
  remarketingIntervalCold: integer("remarketing_interval_cold").notNull().default(7),
  followUpReminder: boolean("follow_up_reminder").notNull().default(true),
  followUpConfirmation: boolean("follow_up_confirmation").notNull().default(true),
  followUpPostAppointment: boolean("follow_up_post_appointment").notNull().default(true),
  postAppointmentHoursAfter: integer("post_appointment_hours_after").notNull().default(1),
  followUpReminderTemplate: text("follow_up_reminder_template"),
  followUpConfirmationTemplate: text("follow_up_confirmation_template"),
  followUpPostAppointmentTemplate: text("follow_up_post_appointment_template"),
  remarketingInstructionsHot: text("remarketing_instructions_hot"),
  remarketingInstructionsWarm: text("remarketing_instructions_warm"),
  remarketingInstructionsCold: text("remarketing_instructions_cold"),
  humanTakeoverMinutes: integer("human_takeover_minutes").notNull().default(5),
  telegramBotToken: text("telegram_bot_token"),
  telegramChatId: varchar("telegram_chat_id", { length: 100 }),
  telegramEscalationEnabled: boolean("telegram_escalation_enabled").notNull().default(false),
  noShowEnabled: boolean("no_show_enabled").notNull().default(false),
  noShowPatientContactHoursAfter: integer("no_show_patient_contact_hours_after").notNull().default(24),
  noShowPatientMessage: text("no_show_patient_message"),
  birthdayEnabled: boolean("birthday_enabled").notNull().default(false),
  birthdayHour: integer("birthday_hour").notNull().default(9),
  birthdayMessage: text("birthday_message"),
  audioMode: varchar("audio_mode", { length: 30 }).notNull().default("off"),
  ttsProvider: varchar("tts_provider", { length: 30 }).notNull().default("cartesia"),
  elevenLabsVoiceId: varchar("eleven_labs_voice_id", { length: 100 }),
  cartesiaVoiceId: varchar("cartesia_voice_id", { length: 100 }),
  recoveryEnabled: boolean("recovery_enabled").notNull().default(false),
  recoveryInactivityDays: integer("recovery_inactivity_days").notNull().default(60),
  recoveryNoShowDays: integer("recovery_no_show_days").notNull().default(14),
  recoveryAiInstructions: text("recovery_ai_instructions"),
  recoveryHours: varchar("recovery_hours", { length: 20 }).notNull().default("10,15"),
  recoveryDays: varchar("recovery_days", { length: 20 }).notNull().default("1,2,3,4,5,6"),
  recoveryMaxPerRun: integer("recovery_max_per_run").notNull().default(10),
  acceptsInstallments: boolean("accepts_installments"),
  maxInstallments: integer("max_installments"),
  acceptsBoleto: boolean("accepts_boleto"),
  paymentNotes: text("payment_notes"),
  vapiApiKey: text("vapi_api_key"),
  vapiPhoneNumberId: varchar("vapi_phone_number_id", { length: 200 }),
  vapiAssistantId: varchar("vapi_assistant_id", { length: 200 }),
  vapiInboundPhoneNumberId: varchar("vapi_inbound_phone_number_id", { length: 200 }),
  vapiInboundAssistantId: varchar("vapi_inbound_assistant_id", { length: 200 }),
  inboundCallsEnabled: boolean("inbound_calls_enabled").notNull().default(false),
  callVoiceId: varchar("call_voice_id", { length: 100 }),
  callsEnabled: boolean("calls_enabled").notNull().default(false),
  callWindowStart: varchar("call_window_start", { length: 5 }).notNull().default("09:00"),
  callWindowEnd: varchar("call_window_end", { length: 5 }).notNull().default("19:00"),
  callTriggerHotLead: boolean("call_trigger_hot_lead").notNull().default(false),
  callTriggerConfirmation: boolean("call_trigger_confirmation").notNull().default(false),
  callTriggerRecovery: boolean("call_trigger_recovery").notNull().default(false),
  callMaxPerDay: integer("call_max_per_day").notNull().default(5),
  callIntervalHoursAfterWhatsapp: integer("call_interval_hours_after_whatsapp").notNull().default(4),
  // Task #15 — daily unconfirmed appointments alert
  unconfirmedAlertEnabled: boolean("unconfirmed_alert_enabled").notNull().default(true),
  unconfirmedAlertHour: integer("unconfirmed_alert_hour").notNull().default(18),
  tenantTzOffsetHours: integer("tenant_tz_offset_hours").notNull().default(-3),
  automationsPaused: boolean("automations_paused").notNull().default(false),
  remarketingPaused: boolean("remarketing_paused").notNull().default(false),
  followupPaused: boolean("followup_paused").notNull().default(false),
  birthdayPaused: boolean("birthday_paused").notNull().default(false),
  recoveryPaused: boolean("recovery_paused").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const insertDentalSettingsSchema = createInsertSchema(dentalSettingsTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertDentalSettings = z.infer<typeof insertDentalSettingsSchema>;
export type DentalSettings = typeof dentalSettingsTable.$inferSelect;
